# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lights/lights.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import mavsdk_options_pb2 as mavsdk__options__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13lights/lights.proto\x12\x11mavsdk.rpc.lights\x1a\x14mavsdk_options.proto\"I\n\x10SetMatrixRequest\x12\x35\n\rmatrix_colors\x18\x01 \x01(\x0b\x32\x1e.mavsdk.rpc.lights.LightMatrix\"K\n\x11SetMatrixResponse\x12\x36\n\rlights_result\x18\x01 \x01(\x0b\x32\x1f.mavsdk.rpc.lights.LightsResult\"X\n\x0fSetStripRequest\x12\x10\n\x08strip_id\x18\x01 \x01(\r\x12\x33\n\x0cstrip_colors\x18\x02 \x01(\x0b\x32\x1d.mavsdk.rpc.lights.LightStrip\"J\n\x10SetStripResponse\x12\x36\n\rlights_result\x18\x01 \x01(\x0b\x32\x1f.mavsdk.rpc.lights.LightsResult\")\n\x17\x46ollowFlightModeRequest\x12\x0e\n\x06\x65nable\x18\x01 \x01(\x08\"R\n\x18\x46ollowFlightModeResponse\x12\x36\n\rlights_result\x18\x01 \x01(\x0b\x32\x1f.mavsdk.rpc.lights.LightsResult\"\x92\x02\n\x0cLightsResult\x12\x36\n\x06result\x18\x01 \x01(\x0e\x32&.mavsdk.rpc.lights.LightsResult.Result\x12\x12\n\nresult_str\x18\x02 \x01(\t\"\xb5\x01\n\x06Result\x12\x12\n\x0eRESULT_UNKNOWN\x10\x00\x12\x12\n\x0eRESULT_SUCCESS\x10\x01\x12\x14\n\x10RESULT_NO_SYSTEM\x10\x02\x12\x1b\n\x17RESULT_CONNECTION_ERROR\x10\x03\x12\x0f\n\x0bRESULT_BUSY\x10\x04\x12\x18\n\x14RESULT_OUT_OF_BOUNDS\x10\x05\x12\x12\n\x0eRESULT_TIMEOUT\x10\x06\x12\x11\n\rRESULT_FAILED\x10\x07\"\x1c\n\nLightStrip\x12\x0e\n\x06lights\x18\x01 \x03(\r\"<\n\x0bLightMatrix\x12-\n\x06strips\x18\x01 \x03(\x0b\x32\x1d.mavsdk.rpc.lights.LightStrip2\xbb\x02\n\rLightsService\x12\\\n\tSetMatrix\x12#.mavsdk.rpc.lights.SetMatrixRequest\x1a$.mavsdk.rpc.lights.SetMatrixResponse\"\x04\x80\xb5\x18\x01\x12Y\n\x08SetStrip\x12\".mavsdk.rpc.lights.SetStripRequest\x1a#.mavsdk.rpc.lights.SetStripResponse\"\x04\x80\xb5\x18\x01\x12q\n\x10\x46ollowFlightMode\x12*.mavsdk.rpc.lights.FollowFlightModeRequest\x1a+.mavsdk.rpc.lights.FollowFlightModeResponse\"\x04\x80\xb5\x18\x01\x42\x1f\n\x10io.mavsdk.lightsB\x0bLightsProtob\x06proto3')



_SETMATRIXREQUEST = DESCRIPTOR.message_types_by_name['SetMatrixRequest']
_SETMATRIXRESPONSE = DESCRIPTOR.message_types_by_name['SetMatrixResponse']
_SETSTRIPREQUEST = DESCRIPTOR.message_types_by_name['SetStripRequest']
_SETSTRIPRESPONSE = DESCRIPTOR.message_types_by_name['SetStripResponse']
_FOLLOWFLIGHTMODEREQUEST = DESCRIPTOR.message_types_by_name['FollowFlightModeRequest']
_FOLLOWFLIGHTMODERESPONSE = DESCRIPTOR.message_types_by_name['FollowFlightModeResponse']
_LIGHTSRESULT = DESCRIPTOR.message_types_by_name['LightsResult']
_LIGHTSTRIP = DESCRIPTOR.message_types_by_name['LightStrip']
_LIGHTMATRIX = DESCRIPTOR.message_types_by_name['LightMatrix']
_LIGHTSRESULT_RESULT = _LIGHTSRESULT.enum_types_by_name['Result']
SetMatrixRequest = _reflection.GeneratedProtocolMessageType('SetMatrixRequest', (_message.Message,), {
  'DESCRIPTOR' : _SETMATRIXREQUEST,
  '__module__' : 'lights.lights_pb2'
  # @@protoc_insertion_point(class_scope:mavsdk.rpc.lights.SetMatrixRequest)
  })
_sym_db.RegisterMessage(SetMatrixRequest)

SetMatrixResponse = _reflection.GeneratedProtocolMessageType('SetMatrixResponse', (_message.Message,), {
  'DESCRIPTOR' : _SETMATRIXRESPONSE,
  '__module__' : 'lights.lights_pb2'
  # @@protoc_insertion_point(class_scope:mavsdk.rpc.lights.SetMatrixResponse)
  })
_sym_db.RegisterMessage(SetMatrixResponse)

SetStripRequest = _reflection.GeneratedProtocolMessageType('SetStripRequest', (_message.Message,), {
  'DESCRIPTOR' : _SETSTRIPREQUEST,
  '__module__' : 'lights.lights_pb2'
  # @@protoc_insertion_point(class_scope:mavsdk.rpc.lights.SetStripRequest)
  })
_sym_db.RegisterMessage(SetStripRequest)

SetStripResponse = _reflection.GeneratedProtocolMessageType('SetStripResponse', (_message.Message,), {
  'DESCRIPTOR' : _SETSTRIPRESPONSE,
  '__module__' : 'lights.lights_pb2'
  # @@protoc_insertion_point(class_scope:mavsdk.rpc.lights.SetStripResponse)
  })
_sym_db.RegisterMessage(SetStripResponse)

FollowFlightModeRequest = _reflection.GeneratedProtocolMessageType('FollowFlightModeRequest', (_message.Message,), {
  'DESCRIPTOR' : _FOLLOWFLIGHTMODEREQUEST,
  '__module__' : 'lights.lights_pb2'
  # @@protoc_insertion_point(class_scope:mavsdk.rpc.lights.FollowFlightModeRequest)
  })
_sym_db.RegisterMessage(FollowFlightModeRequest)

FollowFlightModeResponse = _reflection.GeneratedProtocolMessageType('FollowFlightModeResponse', (_message.Message,), {
  'DESCRIPTOR' : _FOLLOWFLIGHTMODERESPONSE,
  '__module__' : 'lights.lights_pb2'
  # @@protoc_insertion_point(class_scope:mavsdk.rpc.lights.FollowFlightModeResponse)
  })
_sym_db.RegisterMessage(FollowFlightModeResponse)

LightsResult = _reflection.GeneratedProtocolMessageType('LightsResult', (_message.Message,), {
  'DESCRIPTOR' : _LIGHTSRESULT,
  '__module__' : 'lights.lights_pb2'
  # @@protoc_insertion_point(class_scope:mavsdk.rpc.lights.LightsResult)
  })
_sym_db.RegisterMessage(LightsResult)

LightStrip = _reflection.GeneratedProtocolMessageType('LightStrip', (_message.Message,), {
  'DESCRIPTOR' : _LIGHTSTRIP,
  '__module__' : 'lights.lights_pb2'
  # @@protoc_insertion_point(class_scope:mavsdk.rpc.lights.LightStrip)
  })
_sym_db.RegisterMessage(LightStrip)

LightMatrix = _reflection.GeneratedProtocolMessageType('LightMatrix', (_message.Message,), {
  'DESCRIPTOR' : _LIGHTMATRIX,
  '__module__' : 'lights.lights_pb2'
  # @@protoc_insertion_point(class_scope:mavsdk.rpc.lights.LightMatrix)
  })
_sym_db.RegisterMessage(LightMatrix)

_LIGHTSSERVICE = DESCRIPTOR.services_by_name['LightsService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\020io.mavsdk.lightsB\013LightsProto'
  _LIGHTSSERVICE.methods_by_name['SetMatrix']._options = None
  _LIGHTSSERVICE.methods_by_name['SetMatrix']._serialized_options = b'\200\265\030\001'
  _LIGHTSSERVICE.methods_by_name['SetStrip']._options = None
  _LIGHTSSERVICE.methods_by_name['SetStrip']._serialized_options = b'\200\265\030\001'
  _LIGHTSSERVICE.methods_by_name['FollowFlightMode']._options = None
  _LIGHTSSERVICE.methods_by_name['FollowFlightMode']._serialized_options = b'\200\265\030\001'
  _SETMATRIXREQUEST._serialized_start=64
  _SETMATRIXREQUEST._serialized_end=137
  _SETMATRIXRESPONSE._serialized_start=139
  _SETMATRIXRESPONSE._serialized_end=214
  _SETSTRIPREQUEST._serialized_start=216
  _SETSTRIPREQUEST._serialized_end=304
  _SETSTRIPRESPONSE._serialized_start=306
  _SETSTRIPRESPONSE._serialized_end=380
  _FOLLOWFLIGHTMODEREQUEST._serialized_start=382
  _FOLLOWFLIGHTMODEREQUEST._serialized_end=423
  _FOLLOWFLIGHTMODERESPONSE._serialized_start=425
  _FOLLOWFLIGHTMODERESPONSE._serialized_end=507
  _LIGHTSRESULT._serialized_start=510
  _LIGHTSRESULT._serialized_end=784
  _LIGHTSRESULT_RESULT._serialized_start=603
  _LIGHTSRESULT_RESULT._serialized_end=784
  _LIGHTSTRIP._serialized_start=786
  _LIGHTSTRIP._serialized_end=814
  _LIGHTMATRIX._serialized_start=816
  _LIGHTMATRIX._serialized_end=876
  _LIGHTSSERVICE._serialized_start=879
  _LIGHTSSERVICE._serialized_end=1194
# @@protoc_insertion_point(module_scope)
